{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Satyapriyanka511/upskillcampus/blob/main/Passwordmanager.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import json\n",
        "import os\n",
        "import base64\n",
        "import getpass\n",
        "import random\n",
        "import string\n",
        "\n",
        "FILE = \"vault.json\"\n",
        "\n",
        "# ---------- Helper Functions ----------\n",
        "def load_passwords():\n",
        "    if not os.path.exists(FILE):\n",
        "        return {}\n",
        "    with open(FILE, \"r\") as f:\n",
        "        data = f.read()\n",
        "        if not data:\n",
        "            return {}\n",
        "        decoded = base64.b64decode(data).decode()\n",
        "        return json.loads(decoded)\n",
        "\n",
        "def save_passwords(passwords):\n",
        "    encoded = base64.b64encode(json.dumps(passwords).encode()).decode()\n",
        "    with open(FILE, \"w\") as f:\n",
        "        f.write(encoded)\n",
        "\n",
        "def generate_password(length=12):\n",
        "    chars = string.ascii_letters + string.digits + string.punctuation\n",
        "    return ''.join(random.choice(chars) for _ in range(length))\n",
        "\n",
        "# ---------- Main Features ----------\n",
        "def add_password(passwords):\n",
        "    site = input(\"Enter website/app name: \")\n",
        "    username = input(\"Enter username/email: \")\n",
        "    password = getpass.getpass(\"Enter password (or press Enter to auto-generate): \")\n",
        "    if not password:\n",
        "        password = generate_password()\n",
        "        print(f\"🔑 Generated Password: {password}\")\n",
        "    passwords[site] = {\"username\": username, \"password\": password}\n",
        "    save_passwords(passwords)\n",
        "    print(\"✅ Password added successfully!\")\n",
        "\n",
        "def view_passwords(passwords):\n",
        "    if not passwords:\n",
        "        print(\"No passwords saved yet.\")\n",
        "        return\n",
        "    print(\"\\n🔐 SAVED PASSWORDS:\")\n",
        "    for site, info in passwords.items():\n",
        "        print(f\"\\n🌐 {site}\")\n",
        "        print(f\"👤 {info['username']}\")\n",
        "        print(f\"🔑 {info['password']}\")\n",
        "\n",
        "def search_password(passwords):\n",
        "    site = input(\"Enter website name to search: \")\n",
        "    if site in passwords:\n",
        "        info = passwords[site]\n",
        "        print(f\"\\n🌐 {site}\")\n",
        "        print(f\"👤 {info['username']}\")\n",
        "        print(f\"🔑 {info['password']}\")\n",
        "    else:\n",
        "        print(\"❌ No entry found for that website.\")\n",
        "\n",
        "def delete_password(passwords):\n",
        "    site = input(\"Enter website name to delete: \")\n",
        "    if site in passwords:\n",
        "        del passwords[site]\n",
        "        save_passwords(passwords)\n",
        "        print(\"🗑️ Password deleted successfully!\")\n",
        "    else:\n",
        "        print(\"❌ Website not found.\")\n",
        "\n",
        "# ---------- Main Menu ----------\n",
        "def main():\n",
        "    passwords = load_passwords()\n",
        "    print(\"\\n🔒 WELCOME TO ADVANCED PASSWORD MANAGER 🔒\")\n",
        "\n",
        "    while True:\n",
        "        print(\"\\n===== MENU =====\")\n",
        "        print(\"1. Add New Password\")\n",
        "        print(\"2. View All Passwords\")\n",
        "        print(\"3. Search Password\")\n",
        "        print(\"4. Delete Password\")\n",
        "        print(\"5. Exit\")\n",
        "\n",
        "        choice = input(\"Enter your choice (1–5): \")\n",
        "\n",
        "        if choice == \"1\":\n",
        "            add_password(passwords)\n",
        "        elif choice == \"2\":\n",
        "            view_passwords(passwords)\n",
        "        elif choice == \"3\":\n",
        "            search_password(passwords)\n",
        "        elif choice == \"4\":\n",
        "            delete_password(passwords)\n",
        "        elif choice == \"5\":\n",
        "            print(\"👋 Exiting... All data securely encoded and saved!\")\n",
        "            break\n",
        "        else:\n",
        "            print(\"Invalid choice! Try again.\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()\n"
      ],
      "metadata": {
        "id": "wBJWoQ8mT5fz"
      },
      "execution_count": null,
      "outputs": []
    }
  ],
  "metadata": {
    "colab": {
      "name": "Welcome to Colab",
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}